import type { CurriculumSection, ExtractedLessonItem } from './types';

export const mockedCurriculumSections: CurriculumSection[] = [
  {
    id: 'toc',
    subject: 'Whole Manual',
    title: 'Table of Contents',
    kind: 'table-of-contents',
    sourceLocation: 'Page 1',
    itemCount: 0,
    confidence: 'high',
    defaultIncluded: false,
    note: 'Reference section detected before lesson extraction.',
    sourceOrder: 1,
  },
  {
    id: 'weekly-schedule',
    subject: 'Whole Week',
    title: 'Weekly Schedule Grid',
    kind: 'weekly-schedule',
    sourceLocation: 'Pages 2-3',
    itemCount: 18,
    confidence: 'high',
    defaultIncluded: false,
    note: 'Planning/reference material. Useful for order, but not the only source of truth.',
    sourceOrder: 2,
  },
  {
    id: 'math-lesson-plans',
    subject: 'Math',
    title: 'Arithmetic 4 Lesson Plans',
    kind: 'lesson-plans',
    sourceLocation: 'Pages 12-18',
    itemCount: 7,
    confidence: 'high',
    defaultIncluded: true,
    note: 'Sequential lesson-plan instructions detected.',
    sourceOrder: 3,
  },
  {
    id: 'latin-recitation',
    subject: 'Latin',
    title: 'Latin Recitation and Drill',
    kind: 'lesson-plans',
    sourceLocation: 'Pages 19-21',
    itemCount: 4,
    confidence: 'review',
    defaultIncluded: true,
    note: 'Teacher-led recitation mixed with independent drill.',
    sourceOrder: 4,
  },
  {
    id: 'reading-lesson-plans',
    subject: 'Reading',
    title: 'Reading Lesson Plans',
    kind: 'lesson-plans',
    sourceLocation: 'Pages 22-26',
    itemCount: 3,
    confidence: 'high',
    defaultIncluded: true,
    note: 'Reading assignments and discussion prompts detected.',
    sourceOrder: 5,
  },
  {
    id: 'science-activity',
    subject: 'Science',
    title: 'Science Activity',
    kind: 'lesson-plans',
    sourceLocation: 'Pages 30-32',
    itemCount: 5,
    confidence: 'high',
    defaultIncluded: true,
    note: 'Materials, teacher setup, and student observations detected.',
    sourceOrder: 6,
  },
  {
    id: 'answer-key',
    subject: 'Whole Manual',
    title: 'Answer Key',
    kind: 'answer-key',
    sourceLocation: 'Pages 80-91',
    itemCount: 0,
    confidence: 'high',
    defaultIncluded: false,
    note: 'Reference section detected. Not used for student assignments by default.',
    sourceOrder: 7,
  },
  {
    id: 'appendix-resources',
    subject: 'Resources',
    title: 'Appendix and Resources',
    kind: 'appendix',
    sourceLocation: 'Pages 92-98',
    itemCount: 2,
    confidence: 'review',
    defaultIncluded: false,
    note: 'Optional support material detected.',
    sourceOrder: 8,
  },
];

export const mockedExtractedLessons: ExtractedLessonItem[] = [
  {
    id: 'mp-arithmetic-lesson-32',
    sectionId: 'math-lesson-plans',
    instruction: 'Arithmetic 4 Lesson 32',
    subject: 'Math',
    classification: 'parent-teaching',
    sourceText: 'Arithmetic 4 Lesson 32',
    sourceLocation: 'Page 12, Math Lesson Plans',
    sourceOrder: 1,
    confidence: 'high',
  },
  {
    id: 'mp-teach-lesson',
    sectionId: 'math-lesson-plans',
    instruction: 'Teach lesson',
    subject: 'Math',
    classification: 'parent-teaching',
    sourceText: 'Teach lesson',
    sourceLocation: 'Page 12, Math Lesson Plans',
    sourceOrder: 2,
    confidence: 'high',
  },
  {
    id: 'mp-complete-all-problems',
    sectionId: 'math-lesson-plans',
    instruction: 'Complete all problems',
    subject: 'Math',
    classification: 'student-independent',
    sourceText: 'Complete all problems',
    sourceLocation: 'Page 12, Math Lesson Plans',
    sourceOrder: 3,
    confidence: 'high',
  },
  {
    id: 'mp-odds-together',
    sectionId: 'math-lesson-plans',
    instruction: 'Odds together',
    subject: 'Math',
    classification: 'parent-teaching',
    sourceText: 'Odds together',
    sourceLocation: 'Page 12, Math Lesson Plans',
    sourceOrder: 4,
    confidence: 'review',
  },
  {
    id: 'mp-evens-independent-seatwork',
    sectionId: 'math-lesson-plans',
    instruction: 'Evens independent seatwork',
    subject: 'Math',
    classification: 'student-independent',
    sourceText: 'Evens independent seatwork',
    sourceLocation: 'Page 12, Math Lesson Plans',
    sourceOrder: 5,
    confidence: 'high',
  },
  {
    id: 'mp-oral-review',
    sectionId: 'math-lesson-plans',
    instruction: 'Oral Review',
    subject: 'Math',
    classification: 'review',
    sourceText: 'Oral Review',
    sourceLocation: 'Page 13, Math Lesson Plans',
    sourceOrder: 6,
    confidence: 'high',
  },
  {
    id: 'mp-math-challenge-drill-7-1',
    sectionId: 'math-lesson-plans',
    instruction: 'Memoria Math Challenge Drill 7.1',
    subject: 'Math',
    classification: 'student-independent',
    sourceText: 'Memoria Math Challenge Drill 7.1',
    sourceLocation: 'Page 13, Math Lesson Plans',
    sourceOrder: 7,
    confidence: 'high',
  },
  {
    id: 'latin-recite-vocabulary',
    sectionId: 'latin-recitation',
    instruction: 'Recite vocabulary aloud',
    subject: 'Latin',
    classification: 'parent-teaching',
    sourceText: 'Recite vocabulary aloud',
    sourceLocation: 'Page 19, Latin Recitation and Drill',
    sourceOrder: 8,
    confidence: 'review',
  },
  {
    id: 'latin-copy-forms',
    sectionId: 'latin-recitation',
    instruction: 'Copy forms twice',
    subject: 'Latin',
    classification: 'student-independent',
    sourceText: 'Copy forms twice',
    sourceLocation: 'Page 20, Latin Recitation and Drill',
    sourceOrder: 9,
    confidence: 'high',
  },
  {
    id: 'reading-chapter-6',
    sectionId: 'reading-lesson-plans',
    instruction: 'Read chapter 6',
    subject: 'Reading',
    classification: 'student-independent',
    sourceText: 'Read chapter 6',
    sourceLocation: 'Page 22, Reading Lesson Plans',
    sourceOrder: 10,
    confidence: 'high',
  },
  {
    id: 'reading-discussion',
    sectionId: 'reading-lesson-plans',
    instruction: 'Discuss comprehension questions',
    subject: 'Reading',
    classification: 'parent-teaching',
    sourceText: 'Discuss comprehension questions',
    sourceLocation: 'Page 23, Reading Lesson Plans',
    sourceOrder: 11,
    confidence: 'high',
  },
  {
    id: 'science-gather-materials',
    sectionId: 'science-activity',
    instruction: 'Gather magnet, paper clips, and tray',
    subject: 'Science',
    classification: 'parent-prep',
    sourceText: 'Materials: magnet, paper clips, tray',
    sourceLocation: 'Page 30, Science Activity',
    sourceOrder: 12,
    confidence: 'high',
  },
  {
    id: 'science-observe-magnet',
    sectionId: 'science-activity',
    instruction: 'Observe which objects are attracted to the magnet',
    subject: 'Science',
    classification: 'student-independent',
    sourceText: 'Observe which objects are attracted to the magnet',
    sourceLocation: 'Page 31, Science Activity',
    sourceOrder: 13,
    confidence: 'high',
  },
  {
    id: 'science-record-observations',
    sectionId: 'science-activity',
    instruction: 'Record observations',
    subject: 'Science',
    classification: 'student-independent',
    sourceText: 'Record observations',
    sourceLocation: 'Page 31, Science Activity',
    sourceOrder: 14,
    confidence: 'high',
  },
  {
    id: 'appendix-optional-reading',
    sectionId: 'appendix-resources',
    instruction: 'Optional enrichment reading',
    subject: 'Resources',
    classification: 'optional',
    sourceText: 'Optional: enrichment reading',
    sourceLocation: 'Page 94, Appendix and Resources',
    sourceOrder: 15,
    confidence: 'high',
  },
];
